### ISSUE TITLE
Fix MSRV CI

### ISSUE THREAD

**Issue by yaahc** [eyre-rs/eyre#102]
The CI is failing due to the 1.42 version subset of the test matrix.

https://github.com/eyre-rs/eyre/blob/master/.github/workflows/ci.yml#L69

The reason it is failing seems to be due to `thiserror` requiring the `edition = 2021`. We use `thiserror` in tests and documentation. I see a couple of potential directions we could go in resolving this issue:

* adjust the MSRV test to only build `eyre`, not attempt to run tests
* bump the MSRV to `1.56`, the compiler version for the 2021 edition
* bump the version of the MSRV test but leave the reported MSRV in the readme at the current version and only update that MSRV based on user reports of breakage.
* disable subsets of the tests that use `thiserror` when testing MSRV
* remove thiserror usage entirely

I think I lean toward the first option. I cannot anticipate any situations where we'd see breakage in runtime behavior exercised by tests across versions that we wouldn't catch due to this change. If we build in the old version and tests pass in the current version, we're almost certainly fine.

**Comment by pksunkara** [comment]
@ten3roberts Can this  be closed with your recent MSRV changes?
