### ISSUE TITLE
enable raw mode compatibility for panic & error reports

### ISSUE THREAD

**Issue by slordua** [eyre-rs/eyre#142]
a project I'm working on utilizes raw mode, invoked via `crossterm`

this prints reports all funny.. this is my solution in color_eyre for now, but it would be nice to see this integrated more elegantly. an `enable_raw_mode: bool` in `HookBuilder` could be ok.

```rust
use crossterm::terminal::{disable_raw_mode, enable_raw_mode};

// error
// color_eyre::Handler

impl eyre::EyreHandler for Handler {
    fn debug(
        &self,
        error: &(dyn std::error::Error + 'static),
        f: &mut core::fmt::Formatter<'_>,
    ) -> core::fmt::Result {
        let _ = disable_raw_mode();

        // ..

        let _ = enable_raw_mode();

        Ok(())
    }
}

// panic
pub struct RawModePanic;

impl PanicMessage for RawModePanic {
    fn display(
        &self,
        pi: &std::panic::PanicInfo<'_>,
        f: &mut std::fmt::Formatter<'_>,
    ) -> std::fmt::Result {
        let _ = disable_raw_mode();

        // ..

        Ok(())
    }
}

async fn main() -> Result<()> {
    enable_raw_mode()?;

    color_eyre::config::HookBuilder::default()
        .panic_message(RawModePanic)
        .install()?;

    Ok(())
}
```

for panic, there's no need to re-enable raw mode as we're exiting, but one thing i'm not accounting for here is un-recoverable error, in which case the terminal would be left in raw on exit. need match on ErrorKind perhaps whether to re-enable or something

**Comment by LeoniePhiline** [comment]
Just a contributor, not a maintainer, however here's my opinion:

This is outside the scope of eyre.

What you should do instead is register your own panic hook, replacing eyre's built-in hook.

In this own panic hook, you disable raw mode.

I've taken this approach here - feel free to copy and paste: https://github.com/LeoniePhiline/showcase-dl/blob/main/src/error.rs

**Comment by slordua** [comment]
solved this by just using a guard with drop impl
