### ISSUE TITLE
docs: enclosing in backticks

### ISSUE THREAD

**Issue by LeoniePhiline** [eyre-rs/eyre#169]
Reading https://docs.rs/eyre/latest/eyre/struct.Report.html#display-representations I found that some items should better be enclosed in backticks.

![image](https://github.com/eyre-rs/eyre/assets/22329650/af4dd2a4-75e9-49ac-96d7-cf75dca28f69)

I'll happily fix that, I merely want to ask in advance:

When enclosing parts of strings in backticks, do you then prefer **backticks + quotes**, or **only backticks**?

I personally prefer backticks + quotes, to signify _"this is code, but it's a string literal"_.

**Here an example (look out for the curly braces):**

1. **backticks + quotes**: When you print an error object using `"{}"` or `to_string()`, only the outermost underlying error is printed, not any of the lower level causes. This is exactly as if you had called the `Display` `impl` of the error from which you constructed your `eyre::Report`. [...] To print causes as well using eyre’s default formatting of causes, use the alternate selector `"{:#}"`.
2. **only backticks**: When you print an error object using `{}` or `to_string()`, only the outermost underlying error is printed, not any of the lower level causes. This is exactly as if you had called the `Display` `impl` of the error from which you constructed your `eyre::Report`. [...] To print causes as well using eyre’s default formatting of causes, use the alternate selector `{:#}`.

**Comment by pksunkara** [comment]
Backticks + quotes is okay. Thanks :smile:
