### ISSUE TITLE
Doesn't work correctly with new Rust inline formatting

### ISSUE THREAD

**Issue by RReverser** [eyre-rs/eyre#96]
Nowadays Rust supports inline formatting for variables like `format!("Expected {a} to be {b}")`.

This syntax works correctly in `format!`, `format_args!`, `anyhow!` and a lot of other contexts.

However, in eyre, somewhat surprisingly, it treats the string as a literal and prints without interpolation, even though eyre itself has support for formatting when arguments are passed explicitly. It seems this stems from all macros (`ensure!`, `bail!`, `eyre!`) having a separate branch that catches string literal with no following arguments in a special way:

```rust
macro_rules! eyre {
    ($msg:literal $(,)?) => { ... };
    ($err:expr $(,)?) => { ... };
    ($fmt:expr, $($arg:tt)*) => { ... };
}
```

**Comment by nyurik** [comment]
Seems like an easy fix - should i submit a PR?

**Comment by nyurik** [comment]
Ah, turns out its already been fixed, but has not been released yet. Thx for all the hard work updating it. Can't wait for the new release!

**Comment by RReverser** [comment]
Oh, it was? Where did you see that?

**Comment by nyurik** [comment]
https://github.com/eyre-rs/eyre/blob/master/eyre/build.rs#L63-L69

**Comment by nyurik** [comment]
TBH, the implementation seems a bit convoluted, but I might simply not know enough about it.  Most implementations I have seen simply rely on `format_args!` like so:

```rust
macro_rules! foo {
    ($($arg:tt)+) => {
        format_args!($($arg)+)
    };
}
```

**Comment by RReverser** [comment]
> [`master`/eyre/build.rs#L63-L69](https://github.com/eyre-rs/eyre/blob/master/eyre/build.rs?rgh-link-date=2023-10-18T18%3A35%3A56Z#L63-L69)

I don't understand how the referenced lines are related to feature in question.

**Comment by nyurik** [comment]
They are used https://github.com/eyre-rs/eyre/blob/0b24ae558f4779afccb1dfc4640c57d9922ff70e/eyre/src/lib.rs#L1231-L1234 and in a test https://github.com/eyre-rs/eyre/blob/0b24ae558f4779afccb1dfc4640c57d9922ff70e/eyre/tests/test_macros.rs#L78-L85
